export const ORIGIN_LOCATIONS = [
  'BS West 48',
  'BS Middle 48',
  'BS 72',
  'BS Hopper',
  'BS 42',
  'BS East 48',
  'BS East 60',
  'BS West 60',
  'CG West',
  'CG East',
  'LP West',
  'LP East',
  'Campbell West',
  'Campbell East',
  'Home MFS',
  'Home TC',
  'LR Tight',
  "Jimmy's",
  'RG Bin',
  'RG Small N',
  'RG Small S',
  'BS Old Wet Bin',
  'Saratoga A',
  'Saratoga B',
  'TK Behlen',
  'Beaver',
  'Blaisedell',
  'Broadmoore',
  "Calder's",
  'Camelot',
  'Campbell',
  'Cappys',
  'Castleton',
  'CG',
  'CG 120',
  'CG Lake',
  "Chapin's",
  "Chapman's",
  "Ernie's",
  "Gray's",
  'Grubb 40',
  "Hancher's East",
  "Hancher's West",
  'Home North',
  'Home South',
  "Jimmy's 40",
  'Home West',
  "Howard's",
  'Ioder',
  "Kate's",
  'Kiser',
  'Lawn Ridge North',
  'Lawn Ridge South',
  "LeRoy's",
  'LP 39',
  'LP W 75',
  "Lynch's",
  "Mangold's",
  'Mannix North',
  'Mannix South',
  "Marshall's",
  'McKinsey',
  'McNutt',
  'Milo',
  "Neil's",
  "Norm's",
  "Orlyn's",
  'Palace',
  'RG Arrow',
  'RG Centerville',
  'RG Hazel',
  'RG Hensel',
  'RG House',
  'RG Loren',
  'RG NWRR',
  'RG Santa Fe',
  'RG Shop',
  'RG SWRR',
  "Ruby's",
  'Saratoga',
  'Shallowbrook',
  "Stanley's",
  "Steve's",
  'Stone',
  'The Ridge',
  'Western',
  'Yordy',
] as const;

export const PERSON_OPTIONS = [
  'Karl',
  'Anthony',
  'Ethan',
  'Bob',
  'Connie',
  'Bonnie',
  'Roger',
  'PHF',
  'Mannix',
  'Routh',
] as const;

export const CROP_YEARS = ['2024', '2025', '2026', '2027', '2028'] as const;
